name: Python Coverage Report


on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e .[test]

      - name: Run coverage
        run: |
          uv pip install coverage
          uv run coverage run -m unittest discover  # unittestを用いたテストの実行

      - name: Generate reports
        continue-on-error: true
        run: |
          uvx coverage report  # ターミナル上に結果表示
          uvx coverage html  # HTML形式でカバレッジレポートを出力

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: htmlcov  # HTMLレポートが出力されるディレクトリをアップロード
