name: Example


on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  coverage:
    uses: kazuki0824/uv-cibuildwheel-ruff-coverage-template/.github/workflows/coverage.yml@pure

  CI:
    uses: kazuki0824/uv-cibuildwheel-ruff-coverage-template/.github/workflows/CI.yml@pure
    permissions:
      contents: write
      actions: read

  docs:
    uses: kazuki0824/uv-cibuildwheel-ruff-coverage-template/.github/workflows/docs.yml@main
    permissions:
      contents: write
      pages: write
      id-token: write
