name: Example


on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  coverage:
    uses: kazuki0824/uv-cibuildwheel-ruff-coverage-template/.github/workflows/coverage.yml@main

  CI:
    uses: kazuki0824/uv-cibuildwheel-ruff-coverage-template/.github/workflows/CI.yml@main
    permissions:
      contents: write
      actions: read

  pyodide:
    uses: kazuki0824/uv-cibuildwheel-ruff-coverage-template/.github/workflows/pyodide.yml@main
    permissions:
      contents: write