on:
  workflow_call:

jobs:
  build:
    name: Build wasm wheel
    runs-on: ubuntu-latest

    steps:
      - uses: Kesin11/actions-timeline@v2
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.58

      - name: Prepare prerequisites
        run: |
          uv venv
          uv pip install pyodide-build pip
          # workaround for https://github.com/PyO3/maturin/issues/2549#issuecomment-2797285836
          rustup target add wasm32-unknown-emscripten --toolchain nightly-2024-03-07
          rustup default nightly-2024-03-07

      - name: Build
        run: |
          . ./.venv/bin/activate
          pyodide build
